-- TechPulse AI - Consolidated Supabase Schema
-- This script initializes the complete database schema for the multi-tenant SaaS platform.

-- 1. UTILITIES & FUNCTIONS
-- Handle automatic updated_at timestamp updates
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';


-- 2. TABLE DEFINITIONS

-- Tenant Profiles: Stores user-specific settings and personalization
CREATE TABLE IF NOT EXISTS tenant_profiles (
    user_id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name         TEXT,
    slack_webhook_url TEXT,
    discord_webhook_url TEXT,
    api_token         TEXT,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- Articles: AI-processed news aggregation (Multi-tenant)
CREATE TABLE IF NOT EXISTS articles (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    source_url   TEXT NOT NULL,
    title        TEXT NOT NULL,
    content      TEXT,
    summary      TEXT,
    topics       TEXT[] DEFAULT '{}',
    score        FLOAT DEFAULT 0.0,
    source       VARCHAR(100),
    is_delivered BOOLEAN DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    -- Unique constraint per user to allow different users to track the same URL
    CONSTRAINT articles_source_url_userid_key UNIQUE (source_url, user_id)
);

-- RSS Sources: User-specific feed configurations
CREATE TABLE IF NOT EXISTS rss_sources (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    url        TEXT NOT NULL,
    is_active  BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    -- Unique per user
    CONSTRAINT rss_sources_url_userid_key UNIQUE (url, user_id)
);

-- App Config: User-specific topic preferences and system settings
CREATE TABLE IF NOT EXISTS app_config (
    key        TEXT NOT NULL,
    user_id    UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    value      JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (key, user_id)
);

-- Telemetry: System performance and pipeline health metrics
CREATE TABLE IF NOT EXISTS telemetry (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    service     TEXT NOT NULL, -- 'collector', 'summarizer', 'delivery'
    metric_name TEXT,          -- Flat metric name for UI 2.0
    value       FLOAT8,        -- Flat metric value for UI 2.0
    metrics     JSONB NOT NULL, -- Legacy JSON structure
    success     BOOLEAN DEFAULT TRUE,
    timestamp   TIMESTAMPTZ DEFAULT NOW()
);


-- 3. INDEXES
-- Articles optimization
CREATE INDEX IF NOT EXISTS idx_articles_user_id    ON articles(user_id);
CREATE INDEX IF NOT EXISTS idx_articles_score      ON articles(score DESC);
CREATE INDEX IF NOT EXISTS idx_articles_created_at ON articles(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_is_delivered ON articles(is_delivered) WHERE is_delivered = FALSE;

-- RSS Sources optimization
CREATE INDEX IF NOT EXISTS idx_rss_sources_user_id ON rss_sources(user_id);

-- Telemetry optimization
CREATE INDEX IF NOT EXISTS idx_telemetry_user_id     ON telemetry(user_id);
CREATE INDEX IF NOT EXISTS idx_telemetry_service     ON telemetry(service);
CREATE INDEX IF NOT EXISTS idx_telemetry_timestamp   ON telemetry(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_metric_name ON telemetry(metric_name);


-- 4. TRIGGERS
-- Automatic updated_at handling
CREATE TRIGGER update_tenant_profiles_updated_at
    BEFORE UPDATE ON tenant_profiles
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_rss_sources_updated_at
    BEFORE UPDATE ON rss_sources
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_app_config_updated_at
    BEFORE UPDATE ON app_config
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();


-- 5. ROW LEVEL SECURITY (RLS)
-- Enable RLS on all tables
ALTER TABLE tenant_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE rss_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;

-- Tenant Profiles Policies
CREATE POLICY "Users can view own profile"   ON tenant_profiles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own profile" ON tenant_profiles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own profile" ON tenant_profiles FOR UPDATE USING (auth.uid() = user_id);

-- App Config Policies
CREATE POLICY "Users can view own config"   ON app_config FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own config" ON app_config FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own config" ON app_config FOR UPDATE USING (auth.uid() = user_id);

-- RSS Sources Policies
CREATE POLICY "Users can view own sources"   ON rss_sources FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own sources" ON rss_sources FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own sources" ON rss_sources FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own sources" ON rss_sources FOR DELETE USING (auth.uid() = user_id);

-- Articles Policies
CREATE POLICY "Users can view own articles" ON articles FOR SELECT USING (auth.uid() = user_id);

-- Telemetry Policies
CREATE POLICY "Users can view own telemetry" ON telemetry FOR SELECT USING (auth.uid() = user_id);
