-- TechPulse AI - Master Schema (V2 Final Consolidation)
-- This script contains the complete, unified database state including V2 vector logic.
-- Targeted for initialization of fresh project environments.

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. UTILITY FUNCTIONS
-- Automatically update updated_at timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 3. TABLE DEFINITIONS

-- Tenant Profiles: Multi-tenant account settings
CREATE TABLE IF NOT EXISTS tenant_profiles (
    user_id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name         TEXT,
    slack_webhook_url TEXT,
    discord_webhook_url TEXT,
    api_token         TEXT,
    is_admin          BOOLEAN DEFAULT FALSE,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- RSS Sources: User-specific feed configurations & health metrics
CREATE TABLE IF NOT EXISTS rss_sources (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name              TEXT NOT NULL,
    url               TEXT NOT NULL,
    is_active         BOOLEAN DEFAULT TRUE,
    last_fetched_at   TIMESTAMPTZ,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT rss_sources_url_userid_key UNIQUE (url, user_id)
);

-- Article Events: Thematic clusters for grouping related news
CREATE TABLE IF NOT EXISTS article_events (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id           UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title             TEXT NOT NULL,
    description       TEXT,
    centroid_embedding vector(768),
    article_count     INT DEFAULT 1,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- Articles: AI-processed news entries with semantic embeddings
CREATE TABLE IF NOT EXISTS articles (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    source_id        BIGINT REFERENCES rss_sources(id) ON DELETE SET NULL,
    event_id         UUID REFERENCES article_events(id) ON DELETE SET NULL,
    source_url       TEXT NOT NULL,
    title            TEXT NOT NULL,
    content          TEXT,
    summary          TEXT,
    why_it_matters   TEXT,
    topics           TEXT[] DEFAULT '{}',
    theme            TEXT,
    category         TEXT,
    score            FLOAT DEFAULT 0.0,
    novelty_score    FLOAT DEFAULT 1.0,
    embedding        vector(768),
    source           VARCHAR(100),
    is_delivered     BOOLEAN DEFAULT FALSE,
    v2_processed     BOOLEAN DEFAULT FALSE,
    published_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT articles_source_url_userid_key UNIQUE (source_url, user_id)
);

-- Source Health: Real-time telemetry for ingest quality
CREATE TABLE IF NOT EXISTS source_health (
    source_id         BIGINT NOT NULL REFERENCES rss_sources(id) ON DELETE CASCADE,
    user_id           UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    articles_ingested INT DEFAULT 0,
    articles_delivered INT DEFAULT 0,
    articles_clicked  INT DEFAULT 0,
    duplicate_rate    FLOAT DEFAULT 0.0,
    quality_score     FLOAT DEFAULT 0.5,
    last_ingested_at  TIMESTAMPTZ,
    last_updated      TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (source_id, user_id)
);

-- User Feedback: Direct reinforcement signals
CREATE TABLE IF NOT EXISTS user_feedback (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    article_id  UUID REFERENCES articles(id) ON DELETE CASCADE,
    is_helpful  BOOLEAN NOT NULL,
    comment     TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- App Config: Personalized AI pipeline settings
CREATE TABLE IF NOT EXISTS app_config (
    key        TEXT NOT NULL,
    user_id    UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    value      JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (key, user_id)
);

-- Telemetry: Global pipeline performance metrics
CREATE TABLE IF NOT EXISTS telemetry (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    service     TEXT NOT NULL,
    metric_name TEXT,
    value       FLOAT8,
    metrics     JSONB NOT NULL,
    success     BOOLEAN DEFAULT TRUE,
    timestamp   TIMESTAMPTZ DEFAULT NOW()
);

-- 4. INDEXES
CREATE INDEX IF NOT EXISTS idx_articles_user_id      ON articles(user_id);
CREATE INDEX IF NOT EXISTS idx_articles_score        ON articles(score DESC);
CREATE INDEX IF NOT EXISTS idx_articles_theme        ON articles(theme);
CREATE INDEX IF NOT EXISTS idx_articles_created_at   ON articles(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_embedding    ON articles USING ivfflat (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_events_centroid       ON article_events USING ivfflat (centroid_embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_telemetry_timestamp   ON telemetry(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_rss_sources_user_id   ON rss_sources(user_id);

-- 5. TRIGGERS
CREATE TRIGGER update_tenant_profiles_updated_at BEFORE UPDATE ON tenant_profiles
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_rss_sources_updated_at BEFORE UPDATE ON rss_sources
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_article_events_updated_at BEFORE UPDATE ON article_events
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_app_config_updated_at BEFORE UPDATE ON app_config
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 6. RPC FUNCTIONS

-- Semantic search per user
CREATE OR REPLACE FUNCTION match_articles(
  query_embedding  vector(768),
  match_threshold  float,
  match_count      int,
  p_user_id        uuid
) RETURNS TABLE (id uuid, title text, summary text, why_it_matters text, published_at timestamptz, similarity float)
LANGUAGE sql STABLE AS $$
  SELECT id, title, summary, why_it_matters, published_at, 1 - (embedding <=> query_embedding) AS similarity
  FROM articles WHERE user_id = p_user_id AND embedding IS NOT NULL AND 1 - (embedding <=> query_embedding) > match_threshold
  ORDER BY similarity DESC LIMIT match_count;
$$;

-- Near-duplicate check
CREATE OR REPLACE FUNCTION is_near_duplicate(query_embedding vector(768), dup_threshold float, p_user_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS (SELECT 1 FROM articles WHERE user_id = p_user_id AND embedding IS NOT NULL AND 1 - (embedding <=> query_embedding) >= dup_threshold);
$$;

-- Atomic increment for source ingestion tracking
CREATE OR REPLACE FUNCTION increment_source_ingestion(p_source_id bigint, p_user_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    INSERT INTO source_health (source_id, user_id, articles_ingested)
    VALUES (p_source_id, p_user_id, 1)
    ON CONFLICT (source_id, user_id)
    DO UPDATE SET articles_ingested = source_health.articles_ingested + 1, last_ingested_at = now();
END;
$$;

-- Match thematic clusters
CREATE OR REPLACE FUNCTION match_events_by_centroid(query_embedding vector(768), threshold float, p_user_id uuid)
RETURNS TABLE (id uuid, article_count int, similarity float)
LANGUAGE sql STABLE AS $$
  SELECT id, article_count, 1 - (centroid_embedding <=> query_embedding) AS similarity
  FROM article_events WHERE user_id = p_user_id AND centroid_embedding IS NOT NULL AND 1 - (centroid_embedding <=> query_embedding) >= threshold
  ORDER BY similarity DESC LIMIT 5;
$$;

-- 7. ROW LEVEL SECURITY (RLS)
ALTER TABLE tenant_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE rss_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;

-- Standard tenant isolation policies
CREATE POLICY "Tenant isolation - Profiles" ON tenant_profiles FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Tenant isolation - Sources"  ON rss_sources     FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Tenant isolation - Articles" ON articles        FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Tenant isolation - Events"   ON article_events   FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Tenant isolation - Config"   ON app_config      FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Tenant isolation - Stats"    ON source_health   FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Tenant isolation - Feedback" ON user_feedback   FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Tenant isolation - Telemetry" ON telemetry      FOR ALL USING (auth.uid() = user_id);
